apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "keeper.fullname" . }}
  labels:
    {{- include "keeper.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "watch", "list","patch"]
